-- ============================================================
--
--  Boardupscale — DEPRECATED bootstrap script
--
--  ⚠  This file is no longer used.
--
--  The database schema is now managed exclusively through
--  TypeORM migrations located at:
--
--    services/api/src/database/migrations/
--
--  Migrations are applied automatically on API startup
--  (migrationsRun: true in app.module.ts) or manually via:
--
--    cd services/api
--    npm run migration:run      # apply pending migrations
--    npm run migration:revert   # roll back the last migration
--    npm run migration:show     # list applied / pending migrations
--
--  To generate a new migration after changing an entity:
--
--    npm run migration:generate src/database/migrations/YourMigrationName
--
-- ============================================================
--
--  DO NOT add new SQL to this file.  Add a new TypeORM migration instead.
--
-- ============================================================
