import { cn } from '@/lib/utils'

interface RichTextDisplayProps {
  content: string
  className?: string
}

/**
 * Renders stored HTML rich text content safely.
 * Applies .rich-text-content styles (defined in index.css).
 */
export function RichTextDisplay({ content, className }: RichTextDisplayProps) {
  if (!content || content === '<p></p>') return null

  return (
    <div
      className={cn('rich-text-content', className)}
      // Safe: content is generated by TipTap from the same origin — no user-injected raw HTML
      dangerouslySetInnerHTML={{ __html: content }}
    />
  )
}
